### ISSUE TITLE
期权 点完组合配置，有下面触发异常，帮忙解释一下，谢谢，然后t型报价，希腊值都是灰色按钮

### ISSUE THREAD

**Issue by chatphoto** [vnpy/vnpy_optionmaster#15]
我是先装的python,再手动安装veighna。其他cta策略、回测、组合、数据加载等都没问题，可以使用。

vnpy_optionmaster版本：Metadata-Version: 2.1 Name: vnpy-optionmaster Version: 1.0.7
晚上交易时间，用simnow里的第一组ip连接。。哪个合约都报错。。好比cu2310和cu312我已经订阅成功，有日志输出，有跳动。。我再点击optionmaster图标，选择cu_o.shfe，点配置，选cu2310和cu2312，点确定就报错，t型报价，希腊值等都是灰色点不了。
但行情显示中全部出现cu2310和2312的所有call和put的价格跳动。
报错信息是：
Traceback (most recent call last):
File "C:\Users\54364\AppData\Local\Programs\Python\Python310\lib\site-packages\vnpy_optionmaster\ui\widget.py", line 309, in update_portfolio_setting
result: bool = self.option_engine.init_portfolio(self.portfolio_name)
File "C:\Users\54364\AppData\Local\Programs\Python\Python310\lib\site-packages\vnpy_optionmaster\engine.py", line 302, in init_portfolio
holding: PositionHolding = converter.get_position_holding(instrument.vt_symbol)
AttributeError: 'NoneType' object has no attribute 'get_position_holding'

**Comment by noranhe** [comment]
可以用最新版本，等待主界面“合约信息查询成功”日志输出后再启动模块试试看
